name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '7.0'

    - name: Build and Publish
      run: |
        dotnet build --configuration Release
        dotnet publish --configuration Release -o ./publish
      working-directory: ./BlazorUI

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./BlazorUI/publish/wwwroot
        
          # changes the base-tag in index.html from '/' to 'BlazorUI' to match GitHub Pages repository subdirectory
    - name: Change base-tag in index.html from / to BlazorUI
      run: sed -i 's/<base href="\/" \/>/<base href="\/BlazorUI\/" \/>/g' BlazorUI/wwwroot/index.html

      # add .nojekyll file to tell GitHub pages to not treat this as a Jekyll project. (Allow files and folders starting with an underscore)
    - name: Add .nojekyll file
      run: touch BlazorUI/wwwroot/.nojekyll
